### PR TITLE
Feature/source command

### PR DESCRIPTION
**Pull request by elmarsan**
This pull request adds new `source` command for include tape commands into other tape.
It's based on #133 and #220 

### Example

demo.tape 
```
Output ./tapes/demo.gif

Set FontSize 32
Set Width 1200
Set Height 600
Set LoopOffset 50%

Type "echo 'Welcome to VHS!'" Sleep 500ms  Enter

Sleep 1s

Source ./tapes/external.tape

Type "Thanks for the help external tape :)"
```

external.tape
```
Type "echo 'I'm an external tape'" Enter
Enter
Sleep 1s

Type "Goodbye friend"
Enter
Sleep 1s
```

Screenshot from 2023-04-01 16-56-47

### Wrong example

Screenshot from 2023-04-01 17-00-22

### CODE REVIEW

**Comment by maaslalani** [comment]
Hey @elmarsan, this is really awesome work. I'll try and review / polish this up soon.

One thing to think about / test is if you can have a `Source` command within a `Source`d file. I think it would be fine to not allow this if it's tricky but we should provide proper error messages and such to the user.

Otherwise if we do plan on supporting nested sourcing it should likely indent one level deeper. Also, we should have some mechanism to ensure you can perform a cyclic source otherwise you would get infinite recursion.

**Comment by elmarsan** [comment]
> Hey @elmarsan, this is really awesome work. I'll try and review / polish this up soon.
> 
> One thing to think about / test is if you can have a `Source` command within a `Source`d file. I think it would be fine to not allow this if it's tricky but we should provide proper error messages and such to the user.
> 
> Otherwise if we do plan on supporting nested sourcing it should likely indent one level deeper. Also, we should have some mechanism to ensure you can perform a cyclic source otherwise you would get infinite recursion.

Hey @maaslalani thanks!

With the current code you cannot use a `Source` command within a `Source` file. I decided to follow this approach for simplicity.
It might be useful allow nested `Source` thus we need to take a decision.
Let me know what you prefer and I can do it.

**Comment by maaslalani** [comment]
I think for simplicity that's good that we don't allow double nesting of `Source` commands 👍

**Comment by elmarsan** [comment]
> I think for simplicity that's good that we don't allow double nesting of `Source` commands +1

Cool in that case, Iĺl add more tests to make sure everything is correct.

**Review by spatecon — APPROVED** [review]

**Comment by elmarsan** [comment]
Hey @maaslalani  sorry, it's been a while since we last spoke.

I've added a test to check nested `Source` commands and simplified the existing ones.
Let me know whether the tests are okay or we should add more. 
Thanks!

**Comment by maaslalani** [comment]
Hey @elmarsan, thanks so much for this PR, again!

Very excited to get this merged, I will play around and do some more manual testing soon!

**Comment by maaslalani** [comment]
Hey @elmarsan, mind giving me push access to your repository? I've made some changes and rebased the PR and it's ready to merge!

**Comment by elmarsan** [comment]
> Hey @elmarsan, mind giving me (force) push access to your repository? I've made some changes and rebased the PR and it's ready to merge!

Sure, I've sent you and invitation. Once accepted I'll give you god mode right xD.

**Comment by maaslalani** [comment]
Awesome! I've pushed the latest changes!

**Comment by maaslalani** [comment]
Thanks so much @elmarsan for the awesome work! This is a huge upgrade to VHS ❤️

**Pull request merged**
