### PR TITLE
Feat/screenshot

### PR DESCRIPTION
**Pull request by elmarsan**
**Example**

demo

**Tape**

```Elixir
Output screenshot.gif

Set Margin 30
Set MarginFill blue.jpg
Set WindowBar Rings
Set WindowBar Colorful
Set WindowBarSize 40
Set BorderRadius 10
Set FontSize 32


Type "We love screenshots!"

Screenshot demo.png

Sleep 1s

```

### CODE REVIEW

**Comment by maaslalani** [comment]
This looks quite incredible @elmarsan!!!

**Comment by elmarsan** [comment]
@maaslalani conflicts solved

**Review by caarlos0 — APPROVED** [review]
love this!

**Comment by maaslalani** [comment]
Hey @elmarsan, when testing this I notice the `mask.png` and `bar.png` stay lingering. Are you able to reproduce this as well? Make sure you use a tape file that uses `BorderRadius` and `WindowBar`.

**Comment by elmarsan** [comment]
@maaslalani is everything ok?

**Review by maaslalani — APPROVED** [review]
Thanks so much for all the hard work @elmarsan!

**Pull request merged**
