### PR TITLE
feat: add Set DisableRender option for testing.

### PR DESCRIPTION
**Pull request by PThorpe92**
Flag for disabling rendering #363 

This PR adds a "SET" option 

    set DisableRender <bool>

That does the obvious :smile: and keeps it from executing the ffmpeg command so just .txt output can be dealt more easily for our CI/CD testing plans over at [EZA](https://github.com/eza-community/eza) as can be seen at [#147](https://github.com/eza-community/eza/pull/147)

This was my first time looking at the code base, so please let me know if I missed or overlooked something. Also please let me know if/where you would like tests added for this behavior. All I added was to the default token/parser tests, and I couldn't figure out exactly where a general test for this would go, so please do let me know and I'll add it.
Everything I have tried with `Set DisableRender true` and with output being .txt has worked perfectly. 

Just want to say thanks for a great program, and everything you guys do is awesome :rocket: :rocket:

EDIT: Just ran into this again and figured I'd fix the conflicts.

### CODE REVIEW

**Comment by mbechto** [comment]
I have a similar use case. Can we have this please @maaslalani? 😃

**Comment by PThorpe92** [comment]
> I have a similar use case. Can we have this please ? 😃

Assuming you have the same use case (testing the output of CLI program), You might like to know that we found diffing the txt output to be less than deterministic unfortunately :unamused: 

We ended up going with [trycmd](https://github.com/assert-rs/trycmd) and are working on a program to generate the test cases.

What kind of output are you looking to test? It would prob work for something fairly simple but [eza](https://github.com/eza-community/eza) output got complex to test this way pretty quick

**Comment by maaslalani** [comment]
Hey @PThorpe92, thanks for this PR, I think the concept makes sense to have but I would like to avoid increasing the surface area of the language by adding a new keyword for this feature. What do you think of simply modifying the `Output` to recognize an argument such as `"none"` or `"/dev/null"` or something along these lines:

```elixir
Output none
```

**Comment by PThorpe92** [comment]
Yeah that makes sense to me, I'll make the adjustments this weekend :+1:

**Comment by maaslalani** [comment]
Hey @PThorpe92, thanks for the awesome PR, we really appreciate it.

I think disabling renders makes sense to me. However, the approach I'd like to take is that if the `Output ascii.txt` is specified then we don't render a GIF. That way the user would then have to also specify another `Output out.gif` to actually render the GIF.

I will close this PR for now (just doing some spring cleaning 😄) but feel free to open a new PR if this feature is still needed with the mutually exclusive `Output` version.

**Pull request closed without merging**
